databases:
  - name: ticketapi
    databaseName: ticketapi
    user: ticketapi

services:
  - type: web
    name: ticketapi
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ticketapi.wsgi:application"
    envVars:
      - key: DATABSE_URL
        fromDatabase:
          name: ticketapi
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
