version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          command: |
            pipenv install
          name: Test it
      - run:
          name: Collect static files
          command: |
            pipenv run python manage.py collectstatic --no-input
      - run:
          name: Execute tests
          command: |
            pipenv run python manage.py test
      - run:
          name: Push and Deploy
          command: |
            git push origin ft-deploy2

workflows:
  main:
    jobs:
      - build
