# Generated by Django 4.1.3 on 2022-11-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('PN', 'Pending'), ('CD', 'Closed'), ('SD', 'Solved')], default='PN', max_length=2),
        ),
    ]
