# Generated by Django 4.1.3 on 2022-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed'), ('Solved', 'Solved')], default='Pending', max_length=20),
        ),
    ]
